#定义输出级别和输出平台,控件台输出 appender(目的地)可以有多个
log4j.rootLogger=debug,stdout,debugFile,errorFile
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Threshold=debug
log4j.appender.stdout.ImmediateFlush=true
log4j.appender.stdout.Target=system.err
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%-5p][%d{yyyy-MM-dd HH:mm:ss}][%l]%m%n
log4j.appender.debugFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.debugFile.Threshold=debug
log4j.appender.debugFile.ImmediateFlush=true
log4j.appender.debugFile.File=logs/debug.log
log4j.appender.debugFile.layout=org.apache.log4j.PatternLayout
log4j.appender.debugFile.layout.ConversionPattern=[%-5p][%d{yyyy-MM-dd HH:mm:ss}][%l]%m%n
log4j.appender.errorFile=org.apache.log4j.RollingFileAppender
log4j.appender.errorFile.Threshold=debug
log4j.appender.errorFile.ImmediateFlush=true
log4j.appender.errorFile.File=${catalina.base}/error.log
log4j.appender.errorFile.MaxFileSize=20480KB
log4j.appender.errorFile.MaxBackupIndex=10
log4j.appender.errorFile.layout=org.apache.log4j.PatternLayout
log4j.appender.errorFile.layout.ConversionPattern=[%-5p][%d{yyyy-MM-dd HH:mm:ss}][%l]%m%n